MacDown/Code/Document/MPRenderer.m, MacDown/Code/Extension/hoedown_html_patch.c, MacDown/Code/Extension/hoedown_html_patch.h
For #246, I had started the work a few months ago and finally got around to updating the code. This will always add the required "line-numbers" classname to code blocks and conditionally include the prism line numbers plugin js and css based on a new preference option under syntax highlighting. I'm new to Apple dev, so apologies if the edits to the html preferences xib cause issues.
=> Add option to show line numbers in code blocks

MacDown/Resources/help.md
Fix demonstration of markdown list syntax inside of block quotes.
Improve explanation of lists. Clean up typos and make small changes
following uranusjr's lead.
=> Fix help.md syntax error, plus small improvements.

Gemfile, Podfile.lock, README.md
By using a Gemfile we can force everyone to use the older version of CocoaPods. I've bumped the corresponding issue for the bug to see if it can get a fix too.
=> Use a gemfile to get around the CocoaPods bug

Dependency/peg-markdown-highlight/pmh_grammar.leg
As in the screenshot below syntax highlighting goes a bit wonky sometimes when encountering a math block ($, $$), but it is still rendered correctly. This is because the markdown standard and therefore the peg-markdown-highlight have no concept of math mode.
As a fix I just added the syntax for $ and $$ in the .leg file describing syntax to peg-markdown-highlight. This is not an ideal fix as the code for peg-markdown-highlight is a hard copy in the repository. On the other hand it might not be needed upstream as this is not in the Markdown standard and just needed for the editor.
I changed math to render with the code-syntax highlighting as this seems the most natural. It could imply be changed to pmh_NO_TYPE in order not to have syntax highlighting. (or a own type could be added)
Fixed …
=> Corrected Syntax highlighting for $ and $$ math mode

MacDown/Localization/Base.lproj/MPHtmlPreferencesViewController.xib
It's properly spelled "accessory," not "accesory." See http://www.merriam-webster.com/dictionary/accessory
=> Fix spelling within Preferences -> Rendering

MacDown/Code/Document/MPDocument.m
Observers were not being removed properly before deallocating MPDocument,
when MPDocument is closed programmatically by "Time Machine"
Fixes case: File->Revert on document - canceling or picking a revision would cause exception and crash
fixes: #485
=> Fixed Exception being thrown from File->Revert (Document revision)

macdown-cmd/main.m
Fixes a crash when attempting to open files using `macdown-cmd` with URI reserved characters in the filename.
=> Percent-escape macdown-cmd arguments

MacDown/Code/Document/MPDocument.m, MacDown/Localization/Base.lproj/MainMenu.xib
Based on the code for the unordered list. The command simply uses "1." as the prefix for the ordered lists, rather than worrying about counting.
I'm most uncertain about the IDs for the commands, which I created by modifying the last character of the IDs for the unordered versions. Likely there's a better method for generating them.
=> Add ordered list command

MacDown/Code/Document/MPDocument.m
This PR closes #559, closes #529, closes #349, closes #351, and closes #48. All of these issues are approximately duplicates of the same issue, which is that files modified by other applications aren't reflected in MacDown.
These changes are automatically passed to `[NSDocument -readFromData:ofType:error:]`. All this change does is update the display with the changes, rather than ignore them, which is what's happening now.
Here's how it looks with the new behavior:
As a reminder, here's the old behavior, in which MacDown overwrites external changes without warning:
=> Always display latest version of file

MacDown/Code/Document/MPDocument.m
Closes #557, and closes #497. `untitled.md` is used instead of the default `Untitled` when saving a new file.
=> Include .md extension when saving untitled files

MacDown/MacDown-Info.plist
Files with `markdown` extension should also have the Markdown file icon.
=> Add support for ".markdown" extension

Podfile
Got a build error after setting up MacDown here. There’s a bug in MASPreferences 1.1.2 which has been fixed in 1.1.3. Caused build error “-fobjc-arc is not supported on versions of OS X prior to 10.6”. This PR fixes issue #633.
=> Fixed MASPreferences build error

macdown-cmd/MPArgumentProcessor.m
Changed to standard format.
Changed from:
```
usage: macdown version [option] ... file [file ...]
```
Into:
```
usage: macdown [file ...]
```
=> Modified macdown shell utility usage info

MacDown/Resources/help.md
The URL currently in help.md returns a 404.  I guessed what the URL should be based on the image on the home page, with "-160" added, and it looks like it works.
=> Fix logo image URL

MacDown/Code/Application/MPMainController.h, MacDown/Code/Application/MPMainController.m, MacDown/Code/Preferences/MPPreferences.h, MacDown/Code/Preferences/MPPreferences.m, MacDown/Code/Utility/MPGlobals.h, MacDown/Localization/Base.lproj/MainMenu.xib, macdown-cmd/main.m
Added support for piping text to the `macdown` shell utility.
Example:
`echo "# My new document" | macdown`
MacDown will open with a new untitled document with the content "# My new document"
=> Pipe text to macdown shell utility

MacDown/Code/Application/MPMainController.m
Fix #746 image cache issue. Using private API `[WebCache setDisabled:YES]` to disabled the cache of `WebView`. The cache should be disabled, right? Or is there any reason for keeping it enabled?
Feel so so about using private API. Kinda okay since MacDown isn't in the app store. A long term solution is probably what @uranusjr suggested in the #746 comments - migrating to using `WKWebView` instead of `WebView`. That **might** solve this issue as well.
With this fix image will be reloaded when reloading preview or removing and re-adding the image markdown.
_Side note: Another small nice feature might be to trigger a reload of the preview when MacDown enters foreground? Then changes made to images in another application would automatically be updated when returning to MacDown._
=> Disable WebView's cache

MacDown/Code/Document/MPDocument.m
Fixes #585. Filename is selected on the save panel - not filename. Also
this makes the “hide extension” checkbox work.
=> Save dialog selection fix

README.md
The filename of SVG file has a space in it, so I added a %20 to render properly.
=> Fix to the 'gitter | join chat' badge not showing on README.md

Dependency/peg-markdown-highlight/pmh_grammar.leg
This lets one write \$ to avoid having text between dollar signs marked up as TeX when not intended.
=> Added $ to the list of escapable charachters

Dependency/peg-markdown-highlight/HGMarkdownHighlighter.m
Does not currently happen in MacDown, but if you play around with
HGMarkdownHighlighter in other projects, you're open to a crash here.
=> fix passing NULL paragraph style

README.md
The "*Crappy clones*" tweet is no longer public (or it's been deleted, I can't tell).
Removed the link to the tweet.
=> Crappy Clones Tweet is now protected / not public.

MacDown.xcodeproj/project.pbxproj, MacDown/Code/Application/MPMainController.m, MacDown/Localization/Base.lproj/MainMenu.xib, MacDown/Resources/contribute.md
Added new menu item: Help -> "Contibuting to MacDown"
Uses same approach as the current 'MacDown Help' item.
I haven't fully tested this, due to unrelated issues getting the compile to happen.
=> Fixes #893 Added 'contribute' menu item

MacDown/Resources/Extensions/viz.init.js
Assumption:
- Graphviz images are always in code blocks.
- Code blocks are constructed as `<code>` in `<pre>`.
- The `<code>` has `language-*` class.
Fixes #940.
=> Fix bug of rendering only the first Graphviz image

MacDown/Code/Document/MPDocument.m
This pull request replaces the scrollSync with a new algorithm. The new scroll sync aligns headers and images between the editor pane and the preview pane.
As the user scrolls between two headers, the scroll % between those headers is mirrored in the preview pane. This way, large latex blocks between two headers will scroll faster in the editor than their vertically short preview. Similarly, image tags will scroll much slower in the editor than tall images in the preview pane.
This is related to #21, #287
=> Better scroll sync between editor and preview

MacDown/Resources/Styles/Clearness Dark.css, MacDown/Resources/Styles/Clearness.css, MacDown/Resources/Styles/GitHub.css, MacDown/Resources/Styles/GitHub2.css, MacDown/Resources/Styles/Solarized (Dark).css, MacDown/Resources/Styles/Solarized (Light).css
These commits fix both #948 and #949 so that the PDF output is more predicable for users. This is only a tiny change, but should make a bigger change in improving user experience (particularly for non-technical users). 
I've attached a copy of the changes from the old output and the new (via the Clearness stylesheet) compared to the preview. Hopefully you can see that the updated version is much more representative of the preview. Since this editor is based on Mou, this change also makes MacDown's PDF output behave in a more similar way.
There is still the issue of large headers, which is particularly noticeable in PDF outputs with dark backgrounds, e.g. Clearness Dark
I believe this issue is being discussed as #359, and it may have something to do with actual PDF generation which is …
=> css: Improve PDF output

MacDown/Localization/Base.lproj/MPDocument.xib
While contributing for another improvement, I have noticed the lack of Touch bar support, and came up with a very simple solution:
Integrating the EXACT SAME main window toolbar buttons icons into a nice NSTouchBar object hooked into the SplitView editor.
_Referenced by issue : [#969](https://github.com/MacDownApp/macdown/issues/969)_
=> Proper touch bar support

MacDown/Code/Extension/NSTextView+Autocomplete.m
This commit would resolve #939 , adding auto-complete support for both Latin and East Asian Guillemet.
More specifically:
- Typing left Latin double guillemet`«` will be auto-completed as `«»`.
- Same rule applies to Latin single guillemet `‹`, East Asian double guillemet `《` , and East Asian single guillemet `〈 `.
Unicode Links:
1.  [«](https://www.compart.com/en/unicode/U+00AB)[»](https://www.compart.com/en/unicode/U+00BB)
1.  [《](https://www.compart.com/en/unicode/U+300A)[》](https://www.compart.com/en/unicode/U+300B)
1.  [‹](https://www.compart.com/en/unicode/U+2039)[›](https://www.compart.com/en/unicode/U+203A)
1.  [〈](https://www.compart.com/en/unicode/U+3008)[〉](https://www.compart.com/en/unicode/U+3009)
=> Add auto-complete support for Guillemets

MacDown/Resources/help.md
Fixes #1025 by linking all images contained in `help.md` using HTTPS.
=> Use HTTPS links in help.md

MacDown/Localization/Base.lproj/MPMarkdownPreferencesViewController.xib
After some through study of the issue, I could track down the cause of collapsing preferences pane should be related to `autoresizeSubviews`. Interface Builder would warn about ambiguous constraints and AutoLayout stuff, but they are mostly red herrings (unless we ditch OS X 10.8 and switch to `NSStackView`, eliminating most of the painstaking constraints).
This should fix MacDownApp/MacDown#1103.
=> Make preferences pane correctly resize

MacDown/Code/Document/MPDocument.m
=> Check for .md file existence on link click.

README.md
When installing via brew cask install macdown, It shows this warning message : `Calling brew cask install is deprecated! Use brew install [--cask] instead.`
The change was announced in homebrew v2.5.0: https://brew.sh/2020/09/08/homebrew-2.5.0/
=> Calling brew cask install is deprecated
